version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - goenv install --list
      - goenv install 1.20.6 || exit 0
      - goenv global 1.20.6
      - goenv rehash
  pre_build:
    commands:
      - WEBHOOK_EVENT=$GITHUB_EVENT_NAME
      - |
        case "$GITHUB_REF" in
          refs/heads/main)
            ENVIRONMENT_SUFFIX=e1
          ;;
          refs/heads/rc/*)
            ENVIRONMENT_SUFFIX=rc1
          ;;
        esac
      - echo "Config ENVIRONMENT_SUFFIX $ENVIRONMENT_SUFFIX"
      - git status
      - cd $WORKING_DIR
  build:
    commands:
      - aws --version
      - echo "Build started on `date` $WEBHOOK_EVENT $GITHUB_REF"
      - go version
      - go env -w GO111MODULE=on
      - go env
      - echo Building the Docker image...
      - |
        case "$ENVIRONMENT_SUFFIX" in
          rc*)
            TAG=${GITHUB_SHA}.${GITHUB_RUN_ID}
          ;;
        esac
        make build-image TAG=$TAG AWS_VAULT_CMD= && \
        echo "Pushing image && Deploy image ..." && \
        make push-image TAG=$TAG AWS_VAULT_CMD= && \
        make run-deploy TAG=$TAG AWS_VAULT_CMD= ENV=production ENVIRONMENT_SUFFIX=${ENVIRONMENT_SUFFIX}
  post_build:
    commands:
      - echo Build completed on `date`
