// Code generated by MockGen. DO NOT EDIT.
// Source: region.go

// Package mock_infra is a generated GoMock package.
package mock_infra

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRegion is a mock of Region interface.
type MockRegion struct {
	ctrl     *gomock.Controller
	recorder *MockRegionMockRecorder
}

// MockRegionMockRecorder is the mock recorder for MockRegion.
type MockRegionMockRecorder struct {
	mock *MockRegion
}

// NewMockRegion creates a new mock instance.
func NewMockRegion(ctrl *gomock.Controller) *MockRegion {
	mock := &MockRegion{ctrl: ctrl}
	mock.recorder = &MockRegionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegion) EXPECT() *MockRegionMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRegion) Get() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRegionMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegion)(nil).Get))
}
